Repository QEDK/the-road-not-taken, pull requests merged in 2020-10, with the labels that each got.

#14 docs: Create a CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#17 docs: Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#19 Create issue_template.md
  .github/issue_template.md
Labels: documentation

#20 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#22 game: fixed question typos
  src/choices.json
Labels: documentation

#24 🛠️ game: Fix roulette question
  src/choices.json
Labels: bug, frontend, game

#31 game: Add Game over screen and audio
  css/homepage.css
  js/main.js
  src/favicon.ico
  src/theroadnottaken-audio.mp3
Labels: enhancement, frontend, game

#30 docs: Update README with build instructions
  README.md
Labels: documentation
